---
kind: pipeline
name: amd64-pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    dry_run: true
    repo: gitea/test-openldap
    tags: latest-amd64
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    repo: gitea/test-openldap
    tags: latest-amd64
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: arm64-pipeline

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:latest
  settings:
    dry_run: true
    repo: gitea/test-openldap
    tags: latest-arm64
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:latest
  settings:
    repo: gitea/test-openldap
    tags: latest-arm64
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: manifest-latest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  ref:
  - refs/heads/master

depends_on:
- amd64-pipeline
- arm64-pipeline
